In [2]:
import pandas as pd
import numpy as np
import json
import os
import zipfile
import glob
import time
import datetime

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Using the already labelled files from Drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Research stuff/Final Year Design Project/Survey and collected data/Total MindSeer_Data_Collection (Responses) - Form Responses 1.csv')
df.head()

            Timestamp  ... Please attach the file in the following file upload option.
0  11/3/2020 11:23:00  ...  https://drive.google.com/open?id=1-3cRHtc5pU31...
1  11/3/2020 12:55:33  ...  https://drive.google.com/open?id=1BesX6mVyvInx...
2  11/3/2020 14:03:20  ...  https://drive.google.com/open?id=1mXmC2VI9x08E...
3  11/3/2020 14:32:38  ...  https://drive.google.com/open?id=1zQfz3OiA9Tg9...
4  11/3/2020 16:12:37  ...  https://drive.google.com/open?id=1N-Hp4AMFBm4A...

[5 rows x 25 columns]

In [4]:
data=np.array(df)
row,col=data.shape
Class=[]

for i in range(row):
  dif=[7,11,15,19]
  score =0
  l=0
  for j in range(4,25):
    if l<4 and j == dif[l]:
      if(data[i][j][0])=='R':
        score+=3
      elif(data[i][j][0])=='S':
        score+=2
      elif(data[i][j][0])=='O':
        score+=1
      elif(data[i][j][0])=='M':
        score+=0
      l=l+1
    else:
      if(data[i][j][0])=='R':
        score+=0
      elif(data[i][j][0])=='S':
        score+=1
      elif(data[i][j][0])=='O':
        score+=2
      elif(data[i][j][0])=='M':
        score+=3
  if(score<15):
    
    Class.append(0)
  else:
    # data = np.insert(data, 25, 1, axis=1)
    Class.append(1)

In [5]:
len(Class)

104

In [6]:
negative_class = []
positive_class = []
for i in range(len(Class)):
    if Class[i] == 0:
        negative_class.append(i)
    else:
        positive_class.append(i)

print("Negative subjects = ", len(negative_class))
print("Positive subjects = ", len(positive_class))

Negative subjects =  37
Positive subjects =  67

In [7]:
root_path = '/content/drive/MyDrive/Research stuff/Final Year Design Project/Survey and collected data/mindseer_data/'

participants = 0
for name in glob.glob(root_path + '*.zip'): 
    participants += 1

print(participants)

104

In [8]:
#code snippet from https://stackoverflow.com/questions/50008296/facebook-json-badly-encoded

def parse_obj(obj):
    if isinstance(obj, str):
        return obj.encode('latin_1').decode('utf-8')

    if isinstance(obj, list):
        return [parse_obj(o) for o in obj]

    if isinstance(obj, dict):
        return {key: parse_obj(item) for key, item in obj.items()}

    return obj

In [70]:
def data_insert(path, id, data_list):
    try:
        file_present = True
        f = open(path, 'r')
        try:
            raw_data = parse_obj(json.load(f))
            if (path[-6] == '1'):
                json_data = {}
                if type(raw_data) is dict:
                    json_data["posts"] = []
                    json_data["posts"].append(raw_data)
                else:
                    json_data["posts"] = raw_data
                    raw_data = json_data 
        except UnicodeDecodeError as error:
            print(error)
    except FileNotFoundError:
        file_present = False  
        raw_data = {}
    finally:
        #print(raw_data)
        raw_data['participant_id'] = id
        data_list.append(raw_data)
        if file_present:
            f.close()

In [42]:
comments_path = root_path + str(0) + '/comments/comments.json'
data_insert(comments_path, i, [])

{'comments': [{'timestamp': 1603286912, 'data': [{'comment': {'timestamp': 1603286912, 'comment': 'Wuuuvvv eeewwww mooouuuurrrrr', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1603284850, 'data': [{'comment': {'timestamp': 1603284850, 'comment': 'Dhonnobad dost. <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Souradeep Dasgupta's post."}, {'timestamp': 1603284833, 'data': [{'comment': {'timestamp': 1603284833, 'comment': 'Thanks bro. ', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on দীপ চক্রবর্তী's post."}, {'timestamp': 1603284812, 'data': [{'comment': {'timestamp': 1603284812, 'comment': 'Thanks sensei. <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Fatma Tlili's post."}, {'timestamp': 1603284710, 'data': [{'comment': {'timestamp': 1603284710, 'comment': 'Happy to help, man.', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Mubtasim Islam's comment."}, {'timestamp': 1603284593, 'data': [{'comment': {'timestamp': 1603284593, 'comment': 'I guess we are happier now as a couple. Hence the weight gain XD', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1603205748, 'data': [{'comment': {'timestamp': 1603205748, 'comment': 'nah manacche na :P', 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1603205497, 'data': [{'comment': {'timestamp': 1603205497, 'comment': 'Tis okaaayyy....Of course I remember thiss <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1603204241, 'data': [{'comment': {'timestamp': 1603204241, 'comment': 'The irony is the last point is the least important in the actual learning process...', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Shoeb Adnan's comment."}, {'timestamp': 1603203845, 'data': [{'comment': {'timestamp': 1603203845, 'comment': 'Witcher koro plezz', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Pavel Rahman's post."}, {'timestamp': 1603203839, 'data': [{'comment': {'timestamp': 1603203839, 'comment': 'Thanks bro', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Pavel Rahman's post."}, {'timestamp': 1603203831, 'attachments': [{'data': [{'external_context': {'url': 'https://www.youtube.com/watch?v=_O1hM-k3aUY'}}]}], 'data': [{'comment': {'timestamp': 1603203832, 'comment': 'https://www.youtube.com/watch?v=_O1hM-k3aUY', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Pavel Rahman's post."}, {'timestamp': 1603203795, 'data': [{'comment': {'timestamp': 1603203796, 'comment': 'hahahaha', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Pavel Rahman's post."}, {'timestamp': 1603200530, 'data': [{'comment': {'timestamp': 1603200530, 'comment': 'Wait you mean the "Law of Gravity" was not approved by the International Court of Law? :O ', 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1603200135, 'data': [{'comment': {'timestamp': 1603200135, 'comment': 'Stop these NASA liars. The real story was Japan launched explosive canon balls that bombed Pearl Harbor. Because gravity is a lie. :3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Shofiq Saif's photo."}, {'timestamp': 1603199441, 'data': [{'comment': {'timestamp': 1603199441, 'comment': 'Thanks bro', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Iftekhar Hyder's post."}, {'timestamp': 1603199429, 'data': [{'comment': {'timestamp': 1603199429, 'comment': 'Thanks bro! <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Shafi Monjur Khan's post."}, {'timestamp': 1603185084, 'data': [{'comment': {'timestamp': 1603185084, 'comment': "Nothing special. Watching Sakasama no Patema. It's interesting :3", 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1603184094, 'data': [{'comment': {'timestamp': 1603184094, 'comment': 'Thanks dost! Bhalo achish?', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Tamim Bin Zakir's post."}, {'timestamp': 1603184040, 'data': [{'comment': {'timestamp': 1603184040, 'comment': 'Thanks bhaiyya', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Minhaz Morshed Alam's post."}, {'timestamp': 1603184025, 'data': [{'comment': {'timestamp': 1603184025, 'comment': 'Merci beaucoup! :3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Nusrat Jahan Jenny's post."}, {'timestamp': 1603184008, 'data': [{'comment': {'timestamp': 1603184008, 'comment': 'Thank you so muchh! ', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Sunehra Islam Anusha's post."}, {'timestamp': 1603183865, 'data': [{'comment': {'timestamp': 1603183865, 'comment': 'hahahaha....be a bird and excrete from above :3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1603180277, 'data': [{'comment': {'timestamp': 1603180277, 'comment': 'hain. chironidra ekdom D:', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1603180166, 'data': [{'comment': {'timestamp': 1603180166, 'comment': "If you look closely, the guy couldn't take a nap or anything properly. Look how he was gripping the rope with his left hand under the sheets. Karori ghumano possible na emne XD", 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1603179545, 'data': [{'comment': {'timestamp': 1603179545, 'comment': 'Lol. Eto pera neyar dorkar nai. Roomei ghumabo', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1603172655, 'data': [{'comment': {'timestamp': 1603172656, 'comment': 'bichana theke pore gele sheshhhh :P', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1603171062, 'data': [{'comment': {'timestamp': 1603171062, 'comment': 'Thanks bro <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Mahmud Reza's post."}, {'timestamp': 1603171050, 'data': [{'comment': {'timestamp': 1603171050, 'comment': 'Thanks bhaiyya. Hope you and your family are doing well. ', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Ony Erfan's post."}, {'timestamp': 1603171015, 'data': [{'comment': {'timestamp': 1603171015, 'comment': 'Thanks man <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Arpon Kundu's post."}, {'timestamp': 1603170112, 'data': [{'comment': {'timestamp': 1603170112, 'comment': 'Hain next time dekha hoile mone koray dio :3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Kibtyea Tazrian's comment."}, {'timestamp': 1603170034, 'data': [{'comment': {'timestamp': 1603170034, 'comment': 'Thanksss <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Kibtyea Tazrian's post."}, {'timestamp': 1603169234, 'data': [{'comment': {'timestamp': 1603169234, 'comment': 'Thanks dost <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on মেহেদী হাসান's post."}, {'timestamp': 1603168732, 'data': [{'comment': {'timestamp': 1603168732, 'comment': 'Thanks bro. :3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Apel Mahmud's comment."}, {'timestamp': 1603168321, 'data': [{'comment': {'timestamp': 1603168321, 'comment': 'Thanks mami. ', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Sayla Mithun's post."}, {'timestamp': 1603168307, 'data': [{'comment': {'timestamp': 1603168307, 'comment': 'Thanks bhaiyya.', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Ibrahim Hossain's post."}, {'timestamp': 1603168290, 'data': [{'comment': {'timestamp': 1603168290, 'comment': 'Thanks bro! <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Tashfeen Mustafa Choudhury's post."}, {'timestamp': 1603168271, 'data': [{'comment': {'timestamp': 1603168271, 'comment': 'Thanks a lot, Professor. So far so good. How are things at your end?', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Dudley Reynolds's post."}, {'timestamp': 1603168243, 'data': [{'comment': {'timestamp': 1603168243, 'comment': 'Thanks bhaiyya <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Mahi Rabbani's post."}, {'timestamp': 1603168225, 'data': [{'comment': {'timestamp': 1603168225, 'comment': 'Thanks bhai.', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Wahid Bin Mahbub Brinto's post."}, {'timestamp': 1603152552, 'data': [{'comment': {'timestamp': 1603152553, 'comment': 'Thank you Tasnim Kabir Oishee. ', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Tasnim Kabir Oishee's post."}, {'timestamp': 1603099120, 'data': [{'comment': {'timestamp': 1603099120, 'comment': 'block is temporary. As long as you got passion you are going to be persistent. And I suspect you got passion :3', 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1603098963, 'data': [{'comment': {'timestamp': 1603098963, 'comment': 'save them kola brains :3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Maliha Mahzin's post."}, {'timestamp': 1603098239, 'data': [{'comment': {'timestamp': 1603098239, 'comment': 'What I actually do should be you painting mandalas and all them nice arts.', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Kangkhita Hassin's post."}, {'timestamp': 1603034002, 'data': [{'comment': {'timestamp': 1603034002, 'comment': 'Eita deikha Tang khaite munchay', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Suniv Ashraf's post."}, {'timestamp': 1603033232, 'data': [{'comment': {'timestamp': 1603033232, 'comment': 'Indeed!', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Kashpiya Chowdhury's comment."}, {'timestamp': 1602949674, 'data': [{'comment': {'timestamp': 1602949674, 'comment': 'Of courseee sis!', 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1602947186, 'data': [{'comment': {'timestamp': 1602947186, 'comment': 'Congratulations dost! <3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Nawshiba Tasnim Ahmed's photo."}, {'timestamp': 1602894636, 'data': [{'comment': {'timestamp': 1602894636, 'comment': 'Lamia Akter capstone er project 2.5 months e shesh korte parata bishal challenge! ', 'author': 'Akib Fahad', 'group': 'UIU News Feed'}}], 'title': "Akib Fahad replied to Minhaz Al Banna's comment."}, {'timestamp': 1602893661, 'data': [{'comment': {'timestamp': 1602893661, 'comment': 'Snapchat needs to develop a better face reconstruction algorithm. :(', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Muhtasim Fuad's photo."}, {'timestamp': 1602815269, 'data': [{'comment': {'timestamp': 1602815270, 'comment': 'Congratulations bro! ', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Sayed Mehedi Azim's post."}, {'timestamp': 1602814632, 'data': [{'comment': {'timestamp': 1602814632, 'comment': 'More like Akib (X, Y) = (0, 1)', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1602774797, 'data': [{'comment': {'timestamp': 1602774797, 'comment': 'Basically, we want to keep things binary. :3 ', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1602721384, 'data': [{'comment': {'timestamp': 1602721384, 'comment': "Thank god you didn't set Y to infinity XD", 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1602721205, 'data': [{'comment': {'timestamp': 1602721206, 'comment': 'Lmao!', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1602666921, 'data': [{'comment': {'timestamp': 1602666921, 'comment': 'How much food can someone keep eating until it kills him?', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on The Moo Point's photo."}, {'timestamp': 1602658039, 'data': [{'comment': {'timestamp': 1602658039, 'comment': 'I say Polyjuice Potion gone wrong :P', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Suniv Ashraf's comment."}, {'timestamp': 1602657432, 'data': [{'comment': {'timestamp': 1602657432, 'comment': "Nah nose ase. That's a dealbreaker. Hobe na!", 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Suniv Ashraf's comment."}, {'timestamp': 1602647598, 'data': [{'comment': {'timestamp': 1602647598, 'comment': 'Selmon Khun', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Suniv Ashraf's comment."}, {'timestamp': 1602642518, 'data': [{'comment': {'timestamp': 1602642518, 'comment': 'Sad to see Daya having no comebacks to that. Bet he wanted to slap the shit out of that guy XD', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Suniv Ashraf's post."}, {'timestamp': 1602641425, 'data': [{'comment': {'timestamp': 1602641425, 'comment': 'Lies! She already has a bahu with "G". Where\'s that on your list?? :/', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on The ঢঙ's photo."}, {'timestamp': 1602641299, 'data': [{'comment': {'timestamp': 1602641299, 'comment': 'Lol thanks to Lamia Akter for sharing this article :3', 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1602634461, 'attachments': [{'data': [{'external_context': {'url': 'https://alissarumsey.com/intuitive-eating/what-is-intuitive-eating/?fbclid=IwAR0zeHvOfjTPeAA6KrETwiJG99opwoEmuNGTNMwc9Nr7zvXiGMi6T4ljHmw'}}]}], 'data': [{'comment': {'timestamp': 1602634461, 'comment': 'https://alissarumsey.com/intuitive-eating/what-is-intuitive-eating/?fbclid=IwAR0zeHvOfjTPeAA6KrETwiJG99opwoEmuNGTNMwc9Nr7zvXiGMi6T4ljHmw', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Juboraj Naofel's post."}, {'timestamp': 1602633919, 'data': [{'comment': {'timestamp': 1602633920, 'comment': 'I relate to the lazySet method heavily xD', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Mottasin Leemon's comment."}, {'timestamp': 1602539283, 'data': [{'comment': {'timestamp': 1602539283, 'comment': "What's an ass cake and why is it huge? :O", 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Anika Tahsin Prithila's video."}, {'timestamp': 1602539053, 'data': [{'comment': {'timestamp': 1602539053, 'comment': 'Isshh ki hasshiiii... *melts*', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Anika Tahsin Prithila's video."}, {'timestamp': 1602507274, 'data': [{'comment': {'timestamp': 1602507274, 'comment': 'This is the sigil for House Satan, duh!', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Kashpiya Chowdhury's post."}, {'timestamp': 1602389880, 'data': [{'comment': {'timestamp': 1602389880, 'comment': 'Happy birthday, sir! Live long and prosper! 🖖', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Rafeed Rahman's post."}, {'timestamp': 1602388063, 'data': [{'comment': {'timestamp': 1602388063, 'comment': 'Oh if my voice could reach back through the past, I\'d whisper in your ear, "Oh darling, I wish you were here." <3 💙💚', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1602342074, 'data': [{'comment': {'timestamp': 1602342074, 'comment': 'Gaja kheye hallucinate o kortese :P', 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1602321501, 'data': [{'comment': {'timestamp': 1602321501, 'comment': 'Din dupure gorom er moddhe kemne gaja khaw Sardar Moktadir? XD', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Sardar Moktadir's post."}, {'timestamp': 1602212116, 'data': [{'comment': {'timestamp': 1602212116, 'comment': "Ah 2014, the year when we were all thin :')", 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Maliha Mahzin's photo."}, {'timestamp': 1602025741, 'data': [{'comment': {'timestamp': 1602025741, 'comment': 'Low-key Tangled xD', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601985974, 'data': [{'comment': {'timestamp': 1601985974, 'comment': 'The elements of truth hidden within the fable is not pleasant most of the times...', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Nausheen Tabassum Rafa's comment."}, {'timestamp': 1601985765, 'data': [{'comment': {'timestamp': 1601985765, 'comment': "Perfect fitting is sweet :')", 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Mottasin Leemon's comment."}, {'timestamp': 1601977533, 'data': [{'comment': {'timestamp': 1601977533, 'comment': 'Underfiting, overfitting :p', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Tasnim Kabir Oishee's comment."}, {'timestamp': 1601976320, 'data': [{'comment': {'timestamp': 1601976320, 'comment': "Liars aren't going to heaven. I rest my case. :P", 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601974601, 'data': [{'comment': {'timestamp': 1601974601, 'comment': 'I am not going to heaven most likely. :P', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601974558, 'data': [{'comment': {'timestamp': 1601974558, 'comment': 'Actually scratch that', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601974548, 'data': [{'comment': {'timestamp': 1601974548, 'comment': 'For me', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601974540, 'data': [{'comment': {'timestamp': 1601974540, 'comment': 'Harem of Pri clones :3 ', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601974208, 'data': [{'comment': {'timestamp': 1601974208, 'comment': '4 yearssss', 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1601955430, 'data': [{'comment': {'timestamp': 1601955431, 'comment': '6th Oct 2016 ei toh tomar shathe Pri porichoy koray dise :3', 'author': 'Akib Fahad'}}], 'title': 'Akib Fahad replied to his own comment.'}, {'timestamp': 1601954464, 'data': [{'comment': {'timestamp': 1601954464, 'comment': 'shubho porichiti dibosh, Keya! :3', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Sunshine Stella's post."}, {'timestamp': 1601953769, 'attachments': [{'data': [{'external_context': {'url': 'https://media.tenor.co/images/64d78a3017e543b4847be650d506fc10/tenor.gif?riffsid=TVRRM01UazNPREpmWlE9PTB6S3iFfc9H0XbbnVxPqpfvG57Dv3VoLjsbR7OY9XuQ1BFySmzpFehq7jDdjPnVydb0jTkGLVN78kTG'}}]}], 'data': [{'comment': {'timestamp': 1601953769, 'comment': '', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601953373, 'data': [{'comment': {'timestamp': 1601953373, 'comment': 'Kotorokomer pori re bauuu', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601953132, 'data': [{'comment': {'timestamp': 1601953132, 'comment': 'hurr pori banay dila Pri ke? XD', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601953073, 'data': [{'comment': {'timestamp': 1601953074, 'comment': 'In bengali?', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601953001, 'data': [{'comment': {'timestamp': 1601953001, 'comment': 'Prithila = Earth....', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad replied to Anika Tahsin Prithila's comment."}, {'timestamp': 1601921048, 'data': [{'comment': {'timestamp': 1601921048, 'comment': 'Damn. Sick burn! XD', 'author': 'Akib Fahad'}}], 'title': "Akib Fahad commented on Shadman Sakib Apurbo's post."}, {'timestam

In [71]:
comments_data = []
groups_data = []
posts_data = []


for i in range(participants):
    comments_path = root_path + str(i) + '/comments/comments.json'
    data_insert(comments_path, i, comments_data)

    groups_path = root_path + str(i) + '/groups/your_posts_and_comments_in_groups.json'
    data_insert(groups_path, i, groups_data)

    posts_path = root_path + str(i) + '/posts/your_posts_1.json'
    data_insert(posts_path, i, posts_data)

In [72]:
print(len(comments_data))
print(len(groups_data))
print(len(posts_data))

104
104
104

In [92]:
negative_count = 0
positive_count = 0

In [93]:
negative_user_comments_count = 0
positive_user_comments_count = 0
comments_with_timestamps = []

for i in range(participants):
    try:
        for comment_details in comments_data[i]['comments']:
            #print(comment_details)
            try:
                for data in comment_details['data']:
                    comment = {}
                    comment['user_id'] = i
                    comment['text'] = data['comment']['comment']
                    comment['timestamp'] = data['comment']['timestamp']
                    # text += (data['comment']['comment'] + " ")
                    comments_with_timestamps.append(comment)
                    if i in negative_class:
                        negative_count += 1
                        negative_user_comments_count += 1
                    else:
                        positive_count += 1
                        positive_user_comments_count += 1

            except KeyError:
                comment = {}
                comment['user_id'] = i
                comment['text'] = None
                comment['timestamp'] = None
                comments_with_timestamps.append(comment)
                continue
    except KeyError:
        comment = {}
        comment['user_id'] = i
        comment['text'] = None
        comment['timestamp'] = None
        comments_with_timestamps.append(comment)
        continue
    
    # finally:
    #     #print(text)
    #     comment_texts.append(text)

In [94]:
#print('length of comments list =', len(comments_with_timestamps))
print("total comments made by positive class =", positive_user_comments_count)
print("total comments made by negative class =", negative_user_comments_count)

total comments made by positive class = 50202
total comments made by negative class = 34510

In [95]:
negative_user_posts_count = 0
positive_user_posts_count = 0
posts_with_timestamps = []
# posts_texts = []

for i in range(participants):
    try:
        for post_details in posts_data[i]["posts"]:
            #print(post)
            post = {}
            post['user_id'] = i
            post['timestamp'] = post_details['timestamp']
            try:
                for data in post_details['data']:
                    #print(data)
                    if 'post' in data:
                        post['text'] = data['post']
                    else:
                        post['text'] = None
                    
                    posts_with_timestamps.append(post)

                    if i in negative_class:
                        negative_count += 1
                        negative_user_posts_count += 1
                    else:
                        positive_count += 1  
                        positive_user_posts_count += 1
            except KeyError:
                post['text'] = None
                posts_with_timestamps.append(post)
                continue                 
    except KeyError:
        post = {}
        post['user_id'] = i
        post['timestamp'] = None
        post['text'] = None
        continue

    # finally:
    #     posts_texts.append(text)

In [96]:
#print('length of posts list=', len(posts_with_timestamps))
print("total posts made by positive class =", positive_user_posts_count)
print("total posts made by negative class =", negative_user_posts_count)

total posts made by positive class = 23800
total posts made by negative class = 14396

In [97]:
negative_user_group_comments_count = 0
positive_user_group_comments_count = 0
negative_user_group_posts_count = 0
positive_user_group_posts_count = 0
groups_posts_with_timestamps = []
groups_comments_with_timestamps = []

for i in range(participants):
    try:
        for posts_comments in groups_data[i]["group_posts"]["activity_log_data"]:
            group_post = {}
            group_comment = {}
            group_post['user_id'] = i
            group_comment['user_id'] = i
            try:
                for data in posts_comments['data']:
                    if 'post' in data:
                        group_post['timestamp'] = data['update_timestamp']

                        group_post ['text'] = data['post']

                        if group_post not in groups_posts_with_timestamps:
                            groups_posts_with_timestamps.append(group_post)

                            if i in negative_class:
                                negative_count += 1
                                negative_user_group_posts_count += 1
                            else:
                                positive_count += 1
                                positive_user_group_posts_count += 1

                    elif 'comment' in data:
                        group_comment['timestamp'] = data ['comment']['timestamp']
                        
                        if group_comment not in groups_comments_with_timestamps:
                            groups_comments_with_timestamps.append(group_comment)

                            if i in negative_class:
                                negative_count += 1
                                negative_user_group_comments_count += 1
                            else:
                                positive_count += 1
                                positive_user_group_comments_count += 1
            except KeyError:
                group_post ['text'] = None
                group_post ['timestamp'] = None
                groups_posts_with_timestamps.append(group_post)
                group_comment ['text'] = None
                group_comment ['timestamp'] = None        
                groups_comments_with_timestamps.append(group_comment)
                continue
    except KeyError:
        group_post = {}
        group_comment = {}
        group_post['user_id'] = i
        group_comment['user_id'] = i
        group_post ['text'] = None
        group_post ['timestamp'] = None
        group_comment ['text'] = None
        group_comment ['timestamp'] = None  
        continue
    # finally:
    #     #print(text)
    #     groups_texts.append(text)

In [ ]:
groups_post_with_timestamps[:5]

In [98]:
print('length of group comments list =', len(groups_comments_with_timestamps))
print("total group comments made by positive class =", positive_user_group_comments_count)
print("total group comments made by negative class =", negative_user_group_comments_count)
print()
print('length of group posts list=', len(groups_posts_with_timestamps))
print("total group posts made by positive class =", positive_user_group_posts_count)
print("total group posts made by negative class =", negative_user_group_posts_count)

length of group comments list = 20591
total group comments made by positive class = 9622
total group comments made by negative class = 6484

length of group posts list= 4485
total group posts made by positive class = 0
total group posts made by negative class = 0

In [99]:
negative_count

55390

In [100]:
positive_count

83624

In [24]:
all_text = []
for i in range(participants):
    text = comment_texts[i] + " " + groups_texts[i] + " " + posts_texts[i]
    #print(len(text))
    all_text.append(text)

print(len(all_text))

104

In [25]:
all_text_data = pd.DataFrame(all_text)
all_text_data.head()

                                                   0
0  Wuuuvvv eeewwww mooouuuurrrrr Dhonnobad dost. ...
1  Nahian Rakib Its family for luffy Luffy's fami...
2  Rehnuma Rahman Raisa  Sumaia Dhony In Shaa All...
3  Happy Birthday☺Rehnuma Rahman Raisa OK Sir Sir...
4

In [26]:
all_text_data.shape

(104, 1)

In [27]:
total_df = all_text_data.rename(columns = {0 : 'text'})
total_df.head()

                                                text
0  Wuuuvvv eeewwww mooouuuurrrrr Dhonnobad dost. ...
1  Nahian Rakib Its family for luffy Luffy's fami...
2  Rehnuma Rahman Raisa  Sumaia Dhony In Shaa All...
3  Happy Birthday☺Rehnuma Rahman Raisa OK Sir Sir...
4

In [28]:
total_df['Class'] = Class
total_df.head()

                                                text  Class
0  Wuuuvvv eeewwww mooouuuurrrrr Dhonnobad dost. ...      0
1  Nahian Rakib Its family for luffy Luffy's fami...      0
2  Rehnuma Rahman Raisa  Sumaia Dhony In Shaa All...      0
3  Happy Birthday☺Rehnuma Rahman Raisa OK Sir Sir...      0
4                                                         1

In [ ]:
#Saving to xlsx format
total_df.to_excel('/content/text_data.xlsx', sheet_name = 'Sheet 1', index = False, encoding = 'utf-8')

In [ ]:
ts = 1603033232
datetime.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")

'2020-10-18 15:00:32'